### ISSUE TITLE
clang: error

### ISSUE THREAD

**Issue by oddlily** [oddlily/TurtleFugue#3]
On macOS 10.12 Sierra, I get this error when I try to make. Works fine on Ubuntu 16.04.

```
gcc  -o tf attr.o command.o dstring.o expand.o expr.o help.o history.o keyboard.o macro.o main.o malloc.o output.o pattern.o process.o search.o signals.o socket.o tfio.o tty.o util.o variable.o world.o  -lz -ltermcap -lnet  -lpcre
Undefined symbols for architecture x86_64:
  "_pcre_info", referenced from:
      _complete_macro in macro.o
      _tf_reg_compile_fl in pattern.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [tf] Error 1
make: *** [files] Error 2
```

**Comment by oddlily** [comment]
Fixed by #12
