### ISSUE TITLE
Cannot compile on macOS 10.12 Sierra

### ISSUE THREAD

**Issue by oddlily** [oddlily/TurtleFugue#1]
> malloc.c:15:1: error: unknown type name 'caddr_t'
